### ISSUE TITLE
missing EC public key validation when creating a new Verifier

### ISSUE THREAD

**Issue by thomas-fossati** [veraison/go-cose#115]
Currently, when we instantiate a Verifier we do not check that the supplied public key EC point is on the supposed curve.

This is not best practice.  See for example [BCP225](https://www.rfc-editor.org/rfc/rfc8725.html#section-3.4) in the JWS/JWT context:

> "Some cryptographic operations [...] take inputs that may contain invalid values. This includes points not on the specified elliptic curve or other invalid points (e.g., [Valenta], Section 7.1). The JWS/JWE library itself must validate these inputs before using them, or it must use underlying cryptographic libraries that do so (or both!)."

It'd also result in a `panic` when the go-cose application is built against go1.19.  See go1.19 [release notes](https://tip.golang.org/doc/go1.19):

> "Operating on invalid curve points (those for which the IsOnCurve method returns false, and which are never returned by Unmarshal or by a Curve method operating on a valid point) has always been undefined behavior and can lead to key recovery attacks. If an invalid point is supplied to Marshal, MarshalCompressed, Add, Double, or ScalarMult, they will now panic."

This can potentially widen the DoS surface of a go-cose application.  Users should be shielded from such situation.

**Comment by thomas-fossati** [comment]
> Furthermore, it is a reasonable expectation to be provided with a valid argument to begin with.

I don't know you, but for an old-school derelict like myself input validation has always been no. 1 rule of secure coding practices 😄

> It is interesting though that Go went ahead with a `panic` and not the `error` in such a case.

I agree with you that was a pretty _interesting_ choice -- which makes upfront validation without crashing the caller even more valuable.

**Comment by ivarprudnikov** [comment]
> input validation has always been no. 1 rule

But you get that key from somewhere, are you saying you do not verify it before using in the library?

**Comment by thomas-fossati** [comment]
> [...] are you saying you do not verify it before using in the library?

at the moment we just check that the underlying type is as expected (see https://github.com/veraison/go-cose/blob/4dbb9a7434cb75b3cbab3a24076002e8b1ee38a5/verifier.go#L45).  [064ff82](https://github.com/veraison/go-cose/commit/064ff828e19d37d1df895234372940541fb7229d) adds the "on curve" test.

**Comment by ivarprudnikov** [comment]
> at the moment we just check that the underlying type is as expected

^^ My question was more about the production code that gets the key from somewhere and passes it to this library for a verification.

Otherwise, I am just trying to understand if it is a good idea to add this curve check to the library, because:
* Currently the library will defer to what the native go implementation does which is either a good idea or not.
* If the library wants to shield from panic, then one needs to be sure to implement the same checks as in native go that result in such a panic which might mean additional burden on maintenance.
* As it stands, folks who use the library need to do the `IsOnCurve(x, y)` check already because otherwise there might be a panic as the library does not do that check for them.
* [Affected methods](https://cs.opensource.google/go/go/+/master:src/crypto/elliptic/params.go;l=115?q=panicIfNotOnCurve&ss=go%2Fgo) are `Marshal, MarshalCompressed, Add, Double, ScalarMult` that would result in a panic. None of these methods are used here it seems
