### ISSUE TITLE
Field/order size confusion in ECDSA signature length

### ISSUE THREAD

**Issue by pornin** [veraison/go-cose#59]
In ecdsa.go, lines [99](https://github.com/veraison/go-cose/blob/8cef769ef52c8fc111a8b1e4da83649f1cb170d0/ecdsa.go#L99) and [113](https://github.com/veraison/go-cose/blob/8cef769ef52c8fc111a8b1e4da83649f1cb170d0/ecdsa.go#L113), the expected length of an ECDSA signature is computed from `curve.Params().BitSize`, which is the size (in bits) of the field in which the point coordinates are expressed (so says [the Go documentation](https://pkg.go.dev/crypto/elliptic@go1.18.1#CurveParams), at least). However, an ECDSA signature is a pair (_r_,_s_) of integers modulo _n_, where _n_ is the order of the subgroup generated by the base point; thus, the size of _n_ should normally be used to infer the signature size, not the size of the field. Depending on the curve, the field size may be arbitrarily greater than the subgroup order; it may also be smaller by 1 bit (and in that case, using the field size for the encoded signature length may lead to value truncation or errors).

RFC 8152 is rather unhelpful here because it just says (section 8.1) that one should use the "key size", through some variable denoted "key_length", neither of which being properly defined. For the three usual NIST curves (P-256, P-384 and P-521), the field size and the subgroup order size happen to be identical, making the point a bit moot. However, `go-cose` inherently supports all curves that can fit in the Go API, and that is very open-ended and may include curves where the field and the order sizes do not match, even after rounding to a length in bytes. In all generality, using the order length is "more correct" than using the field size (and also more in line with pre-existing standards using ECDSA).

I suggest changing these two expressions into `curve.Params().N.BitLen()`, which would use the order length systematically.

**Comment by shizhMSFT** [comment]
Agreed. The `key_length` in RFC8152 8.1 is ambiguous since it does not call out whether `key_length` refers to the private key (modulo `n`) or the public key (modulo `p`). From the ECDSA algorithm, the modulo `n` is more reasonable since `(r, s)` is a pair of integers modulo `n`.

Although the `key_length` is ambiguous, its value is not. Here are the values for the curves used by `go-cose`:
- P256: 256 bits
- P384: 384 bits
- P521: 521 bits

`curve.Params().N.BitLen()` and `curve.Params().BitSize` return the same value for the above curves.

**Note** to non-crypto readers: The params for the above curves are always fixed and will never change.
